ibov_from_year: 2000

ibov_link: {"file":"COTAHIST_A",
            "url":"http://bvmf.bmfbovespa.com.br/InstDados/SerHist/"}

ibov_cols: {"data_pregao", "cod_papel", "nome_resum", "prazo_dias_termo", 
            "moeda","preco_abertura", "preco_maximo", "preco_minimo",
            "preco_medio", "preco_ultimo", "preco_melhor_compra",
            "preco_melhor_venda", "num_negocios", "qtde_titulos", 
            "vol_titulos", "preco_exerc", "indicador_correcao",
            "fator_cotacao", "preco_exerc_pontos"}